apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actas-pdfs-pvc
  namespace: actas-colegio
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actas-output-pvc
  namespace: actas-colegio
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
